### ISSUE TITLE
BREAKING PMMP 3.13.0 API change - AddActorPacket needs string now

### ISSUE THREAD

**Issue by ZizzyZizzy** [thebigsmileXD/apibossbar#10]
I didn't find any documentation of this change, not even in the history or commits for 3.13.0. Grrr

https://github.com/pmmp/PocketMine-MP/blob/3.12.6/src/pocketmine/network/mcpe/protocol/AddActorPacket.php

https://github.com/pmmp/PocketMine-MP/blob/3.13.0/src/pocketmine/network/mcpe/protocol/AddActorPacket.php

`		$this->type = array_search($t = $this->getString(), self::LEGACY_ID_MAP_BC, true);
		if($this->type === false){
			throw new \UnexpectedValueException("Can't map ID $t to legacy ID");
		}`

Has become

`$this->type = $this->getString();`

BossBarAPI now crashes because of a type error due to this change.

**Comment by Ifera** [comment]
Changes to protocol are never mentioned.

**Comment by ZizzyZizzy** [comment]
@JackMD Sure, protocol changes are huge, but changing the type from INT to STRING in a public function seems like something that should be mentioned.

I added this hacky 3.13 fix until I have time to update it properly.

	$type_id = $this->getEntity() instanceof Entity ? $this->getEntity()::NETWORK_ID : static::NETWORK_ID;
        if(preg_match('/^3.13/',$apiver)) {
            if (!isset(AddActorPacket::LEGACY_ID_MAP_BC[$type_id]))
                throw new \UnexpectedValueException("Can't map ID $type_id to legacy ID");
            $pk->type = AddActorPacket::LEGACY_ID_MAP_BC[$type_id];
        } else {
            $pk->type = $type_id;
        }
