### ISSUE TITLE
BossBar gets removed upon changing worlds

### ISSUE THREAD

**Issue by rjworks** [thebigsmileXD/apibossbar#15]
So  I spawned a boss bar, moved to a different world, boss bar still there, then moved back to the previous world, boss bar gone

**Comment by rjworks** [comment]
help pls

**Comment by rjworks** [comment]
i remove and add bossbar to player when they  change worlds

**Comment by rjworks** [comment]
@thebigsmileXD

**Comment by inxomnyaa** [comment]
GitHub is not Discord, nor any kind of chat platform. Stop spamming.

Will check, but only patch for PM4

**Comment by rjworks** [comment]
Ok Then
