### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by OneWalkDev** [thebigsmileXD/apibossbar#29]
![image](https://user-images.githubusercontent.com/23305324/228174368-c4021b5a-1e2c-48be-813e-047fb47c8ea2.png)

I am currently using PMMP 4.17.1 and get this error when I try to start it.
Please fix it.

**Comment by Terpz710** [comment]
Use pocketmine API 5

**Comment by OneWalkDev** [comment]
As of March 2023, but I'll close it now that it's resolved.
